"$schema" = 'https://starship.rs/config-schema.json'
format = '$username$battery$time$all'

[time]
disabled = false
format = '[\[$time\]](bold white) '
time_format = '%R'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'
